social_registry = //a[@href='https://socialregistry.qa1.openg2p.org']
social_registry_admin = //a[@href='https://admin-sr.qa1.openg2p.org/web']
username_field = login
password_field = password
login_button = //button[@type='submit']
reset_link = Reset Password
reset_email_field = //input[@id='login']
confirm_email_button = //button[@type='submit']
confirmation_message = //p[@class='alert alert-success']
reset_password_error_message = p[role='alert']
login_error_message = //p[@class='alert alert-danger']
group_create_button = //a[@class='dropdown-item o_menu_brand d-none d-md-flex']
Registry = //a[@data-menu-xmlid='g2p_registry_base.g2p_main_menu_root']
logout_dropdown = //button[@class='dropdown-toggle py-1 py-lg-0']
logout = //*[text()='Log out']
registry_configuration1 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration2 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration3 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration4 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration5 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration6 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration7 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
registry_configuration8 = //button[@data-menu-xmlid='g2p_registry_base.g2p_configuration_menu_root']
id_type = //a[@data-menu-xmlid='g2p_registry_base.menu_id_type']
create_button = //div[@class='d-none d-xl-inline-flex gap-1']//button[@class='btn btn-primary o_list_button_add']
configurations_data_input = //div[@name='name']//input[@class='o_input']
registrant_tags = //a[@data-menu-xmlid='g2p_registry_base.menu_registrant_tags']
gender_type = //a[@data-menu-xmlid='g2p_registry_base.menu_gender_type']
gender_type_data_input_code = //div[@name='code']//input[@class='o_input']
gender_type_data_input_value = //div[@name='value']//input[@class='o_input']
group_type = //a[@data-menu-xmlid='g2p_registry_group.menu_group_kind']
group_type_data_input = //input[@class='o_input']
group_membership_kind = //a[@data-menu-xmlid='g2p_registry_membership.menu_group_membership_kind']
group_membership_kind_data_input = //div[@name='name']//input[@class='o_input']
relationship = //a[@data-menu-xmlid='g2p_registry_base.menu_relationship']
relationship_name_data_input = //div[@name='name']//input[@class='o_input o_field_translate']
relationship_inverse_name_data_input = //div[@name='name_inverse']//input[@class='o_input o_field_translate']
relationship_bidirectional_checkbox = //div[@name='bidirectional']//input[@class='form-check-input']
source_partner_type_dropdown = //div[@class='o_field_widget o_field_selection' and @name='source_type']
destination_partner_type_dropdown = //div[@class='o_field_widget o_field_selection' and @name='destination_type']
save_relationship = //button[@class='btn btn-primary o_list_button_save']
save_button = //div[@class='o_list_buttons d-flex gap-1 d-empty-none align-items-baseline']//button[@class='btn btn-primary o_list_button_save']
new_button = //div[@class='d-none d-xl-inline-flex gap-1']//button[@class='btn btn-primary o-kanban-button-new']
group_name_field = //input[@placeholder='Enter name of group...']
contact_details = //div[@class='o_notebook_headers']//li[@class='nav-item flex-nowrap cursor-pointer']//a[@name='basic_info']
region = //a[@data-menu-xmlid='g2p_social_registry.menu_region']
address = address_0
region_dropdown = region_0
save = //button[@class='o_form_button_save btn btn-light px-1 py-0 lh-sm']
save_update = //button[@class='btn btn-primary o_list_button_save']
tags = tags_ids_0
kind = kind_0
groups = //a[@data-menu-xmlid='g2p_registry_group.menu_groups_list']
individuals = //a[contains(text(), 'Individuals')]
family_name = family_name_0
given_name = given_name_0
additional_name = addl_name_0
email = email_0
district_dropdown = district_0
birth_place = birth_place_0
date_of_birth = birthdate_0
civil_status = civil_status_0
occupation = occupation_0
income = income_0
gender_dropdown = gender_0
back_to_login = Back to Login
actions = //button[@class ='dropdown-toggle btn btn-secondary']
delete = //i[@class ='fa fa-trash-o me-1 fa-fw oi-fw']
delete_confirmation = //footer[@class='modal-footer justify-content-around justify-content-sm-start flex-wrap gap-1 w-100']//button[@class='btn btn-primary']
table = //table[@class='o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped']
group = //a[@data-menu-xmlid='g2p_registry_group.menu_groups_list']
district_config = //a[@data-menu-xmlid='g2p_registry_base.menu_district_config']
district_input_field = //div[@name='name']//input[@class='o_input']
home_menu = //button[@class='dropdown-toggle' and @title='Home Menu']
registration_portal_user_dropdown = //a[normalize-space()='Registration Portal User']
portal_username = //div[@name='name']//input[@class='o-autocomplete--input o_input']
portal_user_email = //input[@class='o_input' and @id='email_0']
registration_portal_user = //a[@class='fw-bold text-truncate']
list_view = //i[@class='oi oi-view-list']
action_dropdown = //i[@class='fa fa-cog']
grant_portal_access = //span[text()='Grant portal access' and contains(@class, 'dropdown-item')]
grant_access = //button[@name='action_grant_access']//span[text()='Grant Access']
revoke_access = //button[@name='action_revoke_access']//span[text()='Revoke Access']